packages:
  - 'apps/*'
  - 'packages/*'

# pnpm 11 bloquea por seguridad los postinstall. Habilitamos solo los nativos necesarios.
allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  onnxruntime-node: true
